"""empty message

Revision ID: 85acd55fb744
Revises: 
Create Date: 2023-10-26 09:21:18.708074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85acd55fb744'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ask',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('sentence', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    with op.batch_alter_table('ask', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ask_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ask', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ask_email'))

    op.drop_table('ask')
    # ### end Alembic commands ###
